### ISSUE TITLE
modifications needed for 5.0_c

### ISSUE THREAD

**Issue by jeroenvv** [krumboeck/oracle-alfresco#4]
Today I tried your amp with community edition 5.0_c. In this version, mybatis version 3.2.7 is used and some of the ibatis mappings need to be altered. Alfresco starts up without problems when all the {column jdbcType=TYPE} mappings are changed to {column,jdbcType=TYPE} (note the comma).

**Comment by krumboeck** [comment]
Thank you for pointing this out.
Applied a fix for 5.0_b. A version for 5.0_c will follow in the next weeks.

regards,
Bernd
