### ISSUE TITLE
Error with alfresco 4.2.c missing files

### ISSUE THREAD

**Issue by wajdighribiiptech** [krumboeck/oracle-alfresco#5]
Hi ,
I’ve got anerror : Missing files in alfresco\ibatis\org.hibernate.dialect.MySQLInnoDBDialect
avm-insert-SqlMap
activities-select-SqlMap
node-select-children-SqlMap
…
Any idea !

**Comment by krumboeck** [comment]
I've never created a release for alfresco 4.2.c.

Which release/source code version is used for this experiment?
What are the exact install steps?
Partial or complete output of the log file?
Alfresco main configuration file, at least the database section...

**Comment by wajdighribiiptech** [comment]
1: source code downloaded from:
[https://svn.alfresco.com/repos/alfresco-open-mirror/alfresco/COMMUNITYTAGS/V4.2c/root/](here) 

2: manual install: i have copied thefolders **org.alfresco.repo.domain.hibernate.dialect.AlfrescoOracle9Dialect** under **ibatis** and **dbscriptes** folders under the installation directory: 

3: check attached files
[log.txt](https://github.com/krumboeck/oracle-alfresco/files/334793/log.txt)

4:

```
db.driver=oracle.jdbc.OracleDriver

db.name=alfresco

db.url=jdbc:oracle:thin:@IpServer:1521:XE (XE = DBTNSNAME)

db.username=alfresco

db.password=alfresco

db.pool.validate.query=SELECT 1 FROM DUAL
```

PS : this print screen shows the difference between PostgreSQLDialect(in the right side of the pic) and  AlfrescoOracle9Dialect(in the left side of the pic)
![capture](https://cloud.githubusercontent.com/assets/20064231/16379778/ca36fabc-3c73-11e6-8409-594689694e6e.PNG)

**Comment by krumboeck** [comment]
Mixing alfresco 4.2.c with the current master branch (version 5.0.c) does not work.
The alfresco version and the oracle-alfresco branch have to match!

Currently there exist no branch for 4.2.c.
Please use an older or newer alfresco release (e.g. 4.2.f) and the files from the matching branch: https://github.com/krumboeck/oracle-alfresco/tree/4.2_f

**Comment by wajdighribiiptech** [comment]
the problem is that we have our tool based on alfresco 4.2.c, the upgrae methode is difficult in our case, i think there is no solution how to make this feature work against alfresco 4.2.c ?

**Comment by krumboeck** [comment]
I've added an experimental branch for 4.2.c. The changes are untested.
Try it at your own risk!

If it does not work or you need further help then I can only offer commercial support for this issue.

**Comment by wajdighribiiptech** [comment]
Missing files inf the ibatis AlfrescoOracle9Dialect  folder

**Comment by wajdighribiiptech** [comment]
It works!
Tested : 
- Crud Docs/folders
- Crud users/groups
- Crud workflows instances/definitions

**Comment by krumboeck** [comment]
Perfect, I'll close the case now.
